### ISSUE TITLE
Detectron2 COCO-InstanceSegmentation

### ISSUE THREAD

**Issue by deepseek** [zetyquickly/Detectron2toMobile#1]
@zetyquickly 
- What about converting a detectron2 `COCO-InstanceSegmentation` model into onnx.
- What about onnx to tensorrt
- how much gain in inferencing speed did you get.

**Comment by zetyquickly** [comment]
Hi, @deepseek 

1. You can see detectron2 -> ONNX pipeline inside detectron2 repo
2. Haven't tried it yet
3. detectron2 (pytorch) -> ONNX -> Caffe2 gives great boost comparing to detectron2 (pytorch) -> TorchScript

**Comment by deepseek** [comment]
>2. Haven't tried it yet

Why, did you face difficulties. Is it even possible to convert an `InstanceSegmentation` onnx to tensorrt

3. Boost to cpu or gpu, at what percentage to fps.

4. Where you able to run a caffe2 model on an android phone?

**Comment by zetyquickly** [comment]
Hi, @deepseek 

I haven't explored benefits of using TensorRT on mobile devices. Do you have experience in this area?

3. I've tested on CPU and as I can see Caffe2 is 2-3 times faster than TorchScript
4. You can build `speed_benchmark` binary from PyTorch repo for android. It takes model and input and does inference on mobile CPU

**Comment by deepseek** [comment]
Thanks,
I am new to this
