### ISSUE TITLE
Detectron2Mobile

### ISSUE THREAD

**Issue by morganOliveira2018** [zetyquickly/Detectron2toMobile#2]
@zetyquickly Could you help me transform my trained data model on Detectron2 to a Mobile version? Please.

**Comment by zetyquickly** [comment]
Hi, @morganOliveira2018 

This repository is not expected to be used for deploying detectron2 models on mobile. It is an overview of methods that I considered appropriate for such purpose.

Nevertheless, if you have exact demand in detectron2 mobile deployment I can share my expertise with you

**Comment by morganOliveira2018** [comment]
Hi, @zetquickly 
Did you analyze how the performance of Detectron2 metrics? I would like to know your experience with mobile Detectron2 and if you have a code base that you can share.

**Comment by zetyquickly** [comment]
Yes, @morganOliveira2018 
We've written a paper related to what you are looking for https://arxiv.org/abs/2006.15190

In the research we've deployed detectron2 Faster-RCNN based model to mobile CPU and to mobile NPU (Huawei Kirin).
We've used Caffe2 backend available in detectron2. But today d2 also have torchscript support.

Briefly, expect 1 FPS on high-end Android phone during Mask-RCNN inference on image of size 512x512

**Comment by morganOliveira2018** [comment]
Hi, @zetyquickly 
I did the implementation of the Segmentation of instances of Pisces, then at the end of the training, I just want to generate a Mobile model. Could you take a look at my Colab code and give me possible guidance on torchscript? 🙏🏻🙏🏻🙏🏻

**Comment by zetyquickly** [comment]
@morganOliveira2018, sure

**Comment by morganOliveira2018** [comment]
@zetyquickly What is your Colab email?

**Comment by zetyquickly** [comment]
@morganOliveira2018 I can provide the feedback only if notebook will be public

**Comment by morganOliveira2018** [comment]
@zetyquickly Do you know if standardizing the size of images before you start labeling in the Label tool influences the final result of the AP (Average Precision)? Would it be right to standardize the height x width of all the images in the Dataset set?

**Comment by zetyquickly** [comment]
> @zetyquickly Do you know if standardizing the size of images before you start labeling in the Label tool influences the final result of the AP (Average Precision)? Would it be right to standardize the height x width of all the images in the Dataset set?

As I remember detectron2 does inference on images according to max shortest edge parameter in the config. That means will be the same size during processing. And yes, different sizes of images will give you different results of the AP. So, it is needed to choose which image size (hence AP) is ok for you, then fix this size and export the model to mobile

**Comment by morganOliveira2018** [comment]
1. What code did you export the code to mobile, could you share it with me? 

> I tried to convert by command line to Tensorflow (source: Tensorpack ), using this tutorial as a base I tried to run adapting to my case as seen below. I tried to run Colab:
`!python /content/drive/MyDrive/Dataset-fish/convert_d2.py --d2-config detectron2/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml --d2-pkl model_final_f10217.pkl --output R50FPN-d2-converted.npz`

> Output: 

```
** fvcore version of PathManager will be deprecated soon. **** Please migrate to the version in iopath repo. **https://github.com/facebookresearch/iopath ** fvcore version of PathManager will be deprecated soon. 
**** Please migrate to the version in iopath repo. **https://github.com/facebookresearch/iopath Traceback (most recent call last): File "/content/drive/MyDrive/Dataset-fish/convert_d2.py", line 133, in <module> cfg.merge_from_file(args.d2_config) File "/usr/local/lib/python3.6/dist-packages/detectron2/config/config.py", line 30, in merge_from_file 
assert PathManager.isfile(cfg_filename), f"Config file '{cfg_filename}' does not exist!"
AssertionError: Config file 'detectron2/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml' does not exist!
```

@zetyquickly Could you help???

**Comment by zetyquickly** [comment]
@morganOliveira2018 maybe it is needed to pass absolute path to a config file `mask_rcnn_R_50_FPN_3x.yaml`? TensorPack looks for `detectron2` folder and cannot find it

**Comment by zetyquickly** [comment]
Hope, you resolved your issue
